language: node_js

node_js:
  - "4.1"

script:
  - ./node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --browsers PhantomJS

before_script:
  - npm install -g bower
  - npm install
  - bower install
